bank_app/urls.py
from django.urls import path, include
from . import views
from .api import CostumerDetail, CostumerList, LedgerDetail, LedgerList, AccountDetail, AccountList


app_name = 'bank_app'

urlpatterns = [
    path('', views.index, name="index"),
    path('add_user', views.add_user, name="add_user"),
    path('change_rank', views.change_rank, name="change_rank"),
    path('add_account', views.add_account, name="add_account"),
    path('transfer_money', views.transfer_money, name="transfer_money"),
    path('external_transfer', views.external_transfer, name="external_transfer"),
    path('crypto', views.crypto, name="crypto"),
    path('make_loan', views.make_loan, name="make_loan"),
    path('pay_loan', views.pay_loan, name="pay_loan"),
    path('<int:Costumer_id>/', views.account_detail, name="account_detail"),
    path('logout', views.logout, name="logout"),
    path('test_smtp', views.test_smtp, name="test_smtp"),
    path('sendmail/<int:account_id>/', views.sendmail, name="sendmail"),
    # api urls
    path('api/v1/Costumer/<int:pk>/', CostumerDetail.as_view()),
    path('api/v1/Costumer', CostumerList.as_view()),
    path('api/v1/Ledger/<int:pk>/', LedgerDetail.as_view()),
    path('api/v1/Ledger', LedgerList.as_view()),
    path('api/v1/Account/<int:pk>', AccountDetail.as_view()),
    path('api/v1/Account/', AccountList.as_view()),
    path('api/v1/rest-auth/', include('rest_auth.urls')),
    # channel urls
    path('chat/<str:room_name>/', views.room, name='room'),
    path('support_chat', views.support_chat, name="support_chat"),
]

bank_project/urls.py
from django.contrib import admin
from django.urls import path, include
from two_factor.urls import urlpatterns as tf_urls

urlpatterns = [
    path('admin/', admin.site.urls),
    path('bank/', include('bank_app.urls')),
    path('accounts/', include('login_app.urls')),
    path(r'', include(tf_urls)),
    path('api-auth/', include('rest_framework.urls')),



]

bank_app/models.py
import uuid
from django.contrib.auth.models import User
from django.db import models, transaction
from django.db.models import Sum
from uuid import uuid4
from decimal import Decimal


# Create your models here.

class Costumer(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    phone = models.CharField(max_length=15)
    rank = models.CharField(max_length=15, default="Basic")
    is_employee = models.BooleanField(default=False)

    @property
    def can_make_loans(self):
        if self.rank == "Gold" or self.rank == "Silver":
            return True
        else:
            return False

    def __str__(self):
        return f"{self.user} - {self.rank} - {self.can_make_loans}"


class Account(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    name = models.CharField(max_length=40)
    # regnr = models.CharField(max_length=4, default="8000")
    is_account = models.BooleanField(default=True)

    @property
    def balance(self):
        # return Ledger.objects.filter(account=self).aggregate(Sum('amount') or
        # Decimal(0)
        return Ledger.objects.filter(
            account=self).aggregate(
            Sum('amount'))['amount__sum'] or Decimal(0)

    @property
    def is_foreign_account(self):
        if self.regnr == "8000":
            return False
        else:
            return True

    def __str__(self):
        return f"{self.user} - {self.name}"


class Ledger(models.Model):
    account = models.ForeignKey(Account, on_delete=models.CASCADE)
    regnr = models.CharField(max_length=4)
    amount = models.DecimalField(max_digits=10, decimal_places=2)
    text = models.CharField(max_length=75)
    timestamp = models.DateTimeField(auto_now_add=True)
    transaction_id = models.CharField(max_length=100)

    @classmethod
    def transaction(cls, amount, text, debit_account, credit_account, regnr):
        transaction_id = uuid4()
        amount_negative = -int(amount)

        debit_account = Account.objects.get(id=debit_account)
        credit_account = Account.objects.get(id=credit_account)

        with transaction.atomic():

            credit = Ledger()
            credit.account = credit_account
            credit.regnr = regnr
            credit.amount = amount_negative
            credit.text = text
            credit.transaction_id = transaction_id
            credit.save()

            debit = Ledger()
            debit.account = debit_account
            debit.regnr = regnr
            debit.amount = int(amount)
            debit.text = text
            debit.transaction_id = transaction_id
            debit.save()

    def __str__(self):
        return f"Date: {self.timestamp} Comment: {self.text} Amount: {self.amount}$"


class SupportTicket(models.Model):
    userid = models.OneToOneField(User, on_delete=models.CASCADE)
    username = models.CharField(max_length=15)
    uuid = models.UUIDField(primary_key=False, default=uuid.uuid4)

    def __str__(self):
     return f"{self.userid} - {self.username} - {self.uuid}"

bank_app/forms.py
from django import forms
from .models import Costumer


class CostumerForm(forms.ModelForm):
    class Meta:
        model = Costumer
        exclude = ()


class AddCostumer(forms.Form):
    RANKS=[('Gold','Gold'),
    ('Silver','Silver'),('Basic','Basic')]
    phone = forms.CharField()
    rank = forms.ChoiceField(choices=RANKS, widget=forms.RadioSelect)
    is_employee = forms.BooleanField(required=False)

bank_app/views.py
from channels.generic.websocket import WebsocketConsumer
from channels.layers import get_channel_layer
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect, Http404, JsonResponse
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
import requests
from .models import Costumer, Account, Ledger, SupportTicket
from .forms import AddCostumer
from .tasks import get_coins
from django.contrib.auth import authenticate, logout as dj_logout
import json
from uuid import uuid4
import django_rq
from django_rq import job
from . messaging import email_message
from . messaging import email_statement
from django.shortcuts import redirect
from django.core.paginator import EmptyPage, Paginator
from django.urls import resolve
from asgiref.sync import async_to_sync

# Create your views here


@login_required
def index(request):

    costumer_form = AddCostumer()
    users = User.objects.all()
    all_accounts = Account.objects.all()
    accounts = Account.objects.filter(user=request.user, is_account=True)
    loans = Account.objects.filter(user=request.user, is_account=False)

    # get costumer of logged in user, pass it to template
    costumer = Costumer.objects.get(user=request.user)

    # allcoins

    url = "https://coinranking1.p.rapidapi.com/coins"

    headers = {
        'x-rapidapi-key': "d648778688msh6b6a68838125f03p105bdbjsnee44dc3f26d8",
        'x-rapidapi-host': "coinranking1.p.rapidapi.com"
    }

    response = requests.request("GET", url, headers=headers)

    result = response.text
    coins = json.loads(result)
    coinsdata = coins['data']['coins']

    context = {
        'accounts': accounts,
        'loans': loans,
        'all_accounts': all_accounts,
        'users': users,
        'costumer': costumer,
        'costumer_form': costumer_form,
        'coinsdata': coinsdata,
    }

    return render(request, 'bank_app/index.html', context)


def add_user(request):

    costumer_form = AddCostumer()
    costumer = Costumer.objects.get(user=request.user)
    users = User.objects.all()

    paginatedUsers = Paginator(users, 2)  # Show 2 contacts per page.
    page_num = request.GET.get('page', 1)

    try:
        page = paginatedUsers.page(page_num)
    except EmptyPage:
        page = paginatedUsers(1)

    context = {
        'costumer_form': costumer_form,
        'costumer': costumer,
        'users': page,
    }

    if request.method == "POST":
        username = request.POST['username']
        firstname = request.POST['firstname']
        lastname = request.POST['lastname']
        password = request.POST['password']
        email = request.POST['email']
        phone = request.POST['phone']
        rank = request.POST['rank']

        def is_employee(request):
            if request.POST.get('is_employee'):
                return True
            else:
                return False

        user = User.objects.create_user(username, email, password)

        if user:

            user.first_name = firstname
            user.last_name = lastname
            user.save()

            costumer = Costumer()

            costumer.user = user
            costumer.phone = phone
            costumer.is_employee = is_employee(request)
            costumer.rank = rank
            costumer.save()

    return render(request, 'bank_app/employee.html', context)

    # except:
    # return HttpResponse('<h1>Username has already been used - try
    # again</h1>')


def change_rank(request):

    pk = request.POST['pk']
    rank = request.POST['rank']
    user = User.objects.get(pk=pk)
    costumer = Costumer.objects.get(user=user)
    costumer.rank = rank
    costumer.save()

    return HttpResponseRedirect(reverse('bank_app:index'))


def add_account(request):
    pk = request.POST['pk']
    account_name = request.POST['account']
    user = User.objects.get(pk=pk)
    account = Account(user=user, name=account_name)
    account.save()

    return HttpResponseRedirect(reverse('bank_app:index'))


def transfer_money(request):

    costumer = Costumer.objects.get(user=request.user)
    accounts = Account.objects.filter(user=request.user, is_account=True)
    context = {
        'accounts': accounts,
        'costumer': costumer
    }

    if request.method == 'POST':

        credit_id = request.POST['from_account']
        debit_id = request.POST['to_account']
        amount = request.POST['amount']
        regnr = request.POST['regnr']
        text = request.POST['text']

        # check if debit_id exists
        if Account.objects.filter(id=debit_id).exists():
            # check if debit_id is account (not a loan)
            if Account.objects.filter(id=debit_id, is_account=True):
                # check if balance is sufficient
                if Account.objects.get(
                        user=request.user,
                        id=credit_id).balance >= int(amount):

                    Ledger.transaction(
                        amount, text, debit_id, credit_id, regnr)
                    return HttpResponseRedirect(reverse('bank_app:transfer_money'))

                else:
                    return HttpResponse("<h1>Sorry, insufficient funds</h1>")

            else:
                return HttpResponse("<h1>Sorry, receiver account must be an account (not loan)</h1>")

        else:
            return HttpResponse("<h1>Sorry, receiver account doesn't exist</h1>")

    return render(request, 'bank_app/transfer.html', context)


def external_transfer(request):

    if request.method == 'POST':

        credit_id = request.POST['from_account']
        regnr = request.POST['to_regnr']
        debit_id = request.POST['to_account']
        amount = request.POST['amount']
        text = request.POST['text']

        # STEP 1: CHECK FUNDS

        if Account.objects.get(user=request.user, id=credit_id).balance < int(amount):
            return HttpResponse('<h1>Sorry, insufficient funds</h1>')

        # STEP 2: AUTHENTICATE

        payload = {'username': 'admin', 'password': 'admin'}
        r = requests.post(
            f'http://127.0.0.1:{regnr}/bank/api/v1/rest-auth/login/', data=payload)

        token = r.json()['key']
        print(f'Token {token}')

        # STEP 3: CHECK IF RECEIVER ACCOUNT EXISTS

        headers = {'Authorization': f'Token {token}'}
        r = requests.get(
            f'http://127.0.0.1:{regnr}/bank/api/v1/Account/{debit_id}', headers=headers)

        print(r.text)
        print(r.status_code)

        # STEP 4: POST TO REST API

        # Bank account belonging to Bank 8000 inside Bank 4000:
        # Account id: 2

        if r.status_code == 200:
            print('Account exists')

            uuid = uuid4()

            payload_1 = {'account': '2',
                         'regnr': f'{regnr}',
                         'amount': f'-{amount}',
                         'text': f'{text}',
                         'transaction_id': f'{uuid}'
                         }

            payload_2 = {'account': f'{debit_id}',
                         'regnr': f'{regnr}',
                         'amount': f'{amount}',
                         'text': f'{text}',
                         'transaction_id': f'{uuid}'}

            r1 = requests.post(
                f'http://127.0.0.1:{regnr}/bank/api/v1/Ledger', headers=headers, data=payload_1)
            r2 = requests.post(
                f'http://127.0.0.1:{regnr}/bank/api/v1/Ledger', headers=headers, data=payload_2)

            print(r1.status_code)
            print(r2.status_code)

        else:
            return HttpResponse('<h1>Account doesnt exist or external bank is down</h1>')

        # STEP 5: TRANSACTION INTERNALLY

        # Bank account belonging to Bank 4000 inside Bank 8000:
        # Account id: 2

        debit_id = 2
        Ledger.transaction(amount, text, debit_id, credit_id, regnr)

    return render(request, 'bank_app/transfer.html')


def make_loan(request):

    accounts = Account.objects.filter(user=request.user, is_account=True)
    loans = Account.objects.filter(user=request.user, is_account=False)
    costumer = Costumer.objects.get(user=request.user)

    context = {
        'accounts': accounts,
        'loans': loans,
        'costumer': costumer,
    }

    if request.method == 'POST':

        amount = request.POST['amount']
        text = request.POST['text']
        loan_name = request.POST['loan_name']
        regnr = 8000

        # get id of debit account
        account_id = request.POST['account_name']

        account = Account(user=request.user, name=loan_name, is_account=False)
        account.save()

        # get id of credit account
        loan_id = account.id

        # if the given account name exists and belongs to the user

        if Account.objects.filter(user=request.user, id=account_id).exists():
            Ledger.transaction(amount, text, account_id, loan_id, regnr)

    return render(request, 'bank_app/loan.html', context)


def pay_loan(request):

    credit_id = request.POST['from_account']
    debit_id = request.POST['to_account']
    amount = request.POST['amount']
    regnr = request.POST['regnr']
    text = request.POST['text']

    if Account.objects.get(id=debit_id, is_account=False):
        # print('This is a loan account!')
        if Account.objects.get(id=debit_id, user=request.user, is_account=False):
            #print('This loan account belongs to the user')
            #loan_account = Account.objects.get(id=debit_id)
            loan_balance = Account.objects.get(id=debit_id).balance
            loan_balance = abs(int(loan_balance))
            amount = int(amount)

            if Account.objects.get(id=credit_id, user=request.user).balance >= amount:
                #print('You have enough money!')
                if amount >= loan_balance:
                    amount = loan_balance
                    Ledger.transaction(

bank_app/templates/bank_app/account_detail.html
{% extends 'bank_app/base.html' %} {% load humanize %} {% block content %}

<a href="{% url 'bank_app:index' %}"></a>

<h1>user: {{ user }}</h1>

<br />

<h1>Accounts:</h1>

<div>
  {% for account in accounts %}

  <p>Account id: {{ account.id }} // Name: {{ account.name }} // $ {{ account.balance|floatformat:2|intcomma }}</p>
 
  <a href="{% url 'bank_app:sendmail' account_id=account.pk %}">send bank statement for account</a>
 
  {% endfor %}
</div>

<h2>Transactions: 📒</h2>

{% for ledger in ledgers %}

<div style="font-style: italic; margin: 10px 0">
	Account: {{ ledger.account }} <br>  Amount: {{ ledger.amount }} <br>  Message:  {{ ledger.text }}  <br> Time:  {{ ledger.timestamp }}
</div>

{% endfor %} {% endblock %}

bank_app/templates/bank_app/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    {% load static %} <link rel="stylesheet" type="text/css" href="{% static "main/css/main.css" %}"> <link rel="stylesheet"
    type="text/css" href="{% static "bank_app/css/main.css" %}">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/water.css@2/out/light.min.css" />
    <title>Bank</title>
  </head>
  <body>
    <header>
      {% with url_name=request.resolver_match.url_name %}
      <nav>
        <li>
          <a href="{% url 'bank_app:index' %}" class="{% if url_name == 'index' %}active{% endif %}">Home 🏠</a>
        </li>
        <li>
          <a href="{% url 'bank_app:transfer_money' %}" class="{% if url_name == 'transfer_money' %}active{% endif %}">Transfer 💸</a>
        </li>
        <li>
          <a href="{% url 'bank_app:make_loan' %}" class="{% if url_name == 'make_loan' %}active{% endif %}">Loans 💰</a>
        </li>
        <li>
          <a href="{% url 'bank_app:crypto' %}" class="{% if url_name == 'crypto' %}active{% endif %}">Crypto Corner 🐍</a>
        </li>
        {% if costumer.is_employee %}
        <li>
          <a href="{% url 'bank_app:add_user' %}" class="{% if url_name == 'add_user' %}active{% endif %}">Employee Zone 👨‍💼</a>
        </li>
        {% endif %}
        {% if costumer.is_employee is False %}
        {% if url_name != 'room' %}
        <li class="{% if url_name == 'support_chat' %}displayNone{% endif %}">
          <form action="{% url 'bank_app:support_chat' %}" method="POST">
            {% csrf_token %}
            <button>Support Chat 💬</button>
          </form>
        </li>
        {% endif %}
        {% endif %}
        <li>
          <a href="{% url 'bank_app:logout' %}">Logout 👋</a>
        </li>
      </nav>
      {% endwith %}
    </header>

    {% if costumer.is_employee %}
    {% with url_name=request.resolver_match.url_name %}
    {% if url_name != 'room' %}
    <h2>Customer support - Notification Center ⚠️</h2>
    <hr>
    <div class="customer-support">
     
    </div>

    
    <script>

      const chatSocket = new WebSocket("ws://" + window.location.host + "/ws/bank/chat/" + "employeeNotification" + "/");
      console.log(chatSocket);
 
      chatSocket.onopen = function (e) {
      console.log("Websocket up and running, ready for messages captain");
      };

      chatSocket.onmessage = function (e) {
      console.log("new notification!");
      const data = JSON.parse(e.data);
      console.log(data);
      let supportTicket = `<div id="${data.message}" class="employee-notification"> <p> User <strong>${data.username}</strong> has requested support <u>${new Date().toLocaleTimeString('dk-DK', { hour12: false })}</u> at <i><a href="http://localhost:8000/bank/chat/${data.message}">http://localhost:8000/bank/chat/${data.message}</a></i></div>`;
      document.querySelector(".customer-support").insertAdjacentHTML("afterbegin", supportTicket);
      };
    </script>
    {% endif %}
    {% endwith %}
    
    {% endif %}
  

    {% block content %} {% endblock %} {% block footer %} {% endblock %}
    <script type="text/javascript" src="{% static "bank_app/js/script.js" %}"></script>
  </body>
</html>

bank_app/templates/bank_app/crypto.html
{% extends "bank_app/base.html" %} {% block content %}

<h2>Crypto Corner 🐍</h2>

<div class="crypto-table-top crypto-table">
  <div class="abb">Abb.</div>
  <div class="name">Name</div>
  <div>Value</div>
  <div>Change (24h)</div>
  <div>Peak value</div>
</div>

<div class="crypto-content">
  {% for element in coinsdata %} {% load humanize %}

  <div class="crypto-table">
    <img src="{{ element.iconUrl }}" alt="" />
    <div class="abb">{{ element.symbol }}</div>
    <div class="name">{{ element.name }}</div>
    <div>{{ element.price|floatformat:2|intcomma }} $</div>
    <div class="trend">{{ element.change }} %</div>
    <div>{{ element.allTimeHigh.price|floatformat:2|intcomma }} $</div>
  </div>

  {% endfor %}
</div>

<script>
  function numberWithCommas(x) {
    var float = parseFloat(x).toFixed(2);
    var parts = float.toString().split(".");
    parts[0] = parts[0].replace(/\B(?=(\d{3})+(?!\d))/g, ",");
    return parts.join(".");
  }

  function color(x) {
    float = parseFloat(x);
    if (float > 0) {
      return `<div class="trend green">${float} %</div>`;
    }

    if (float == 0) {
      return `<div class="trend gray">${float} %</div>`;
    }

    if (float < 0) {
      return `<div class="trend red">${float} %</div>`;
    }
  }

  var socket = new WebSocket("ws://localhost:8000/ws/coins/");

  socket.onopen = function(event) {
    console.log("opened");
    console.log(event);
  };

  socket.onmessage = function(event) {
    console.log("updated");
    var data = JSON.parse(event.data);
    var cryptocontent = document.querySelector(".crypto-content");
    cryptocontent.innerHTML = "";

    data.forEach(elm => {
      var row = `
      <div class="crypto-table">
        <img src="${elm.iconUrl}" alt="" />
        <div class="abb">${elm.symbol}</div>
        <div class="name">${elm.name}</div>
        <div>${numberWithCommas(elm.price)} $</div>
        ${color(elm.change)}
        <div>${numberWithCommas(elm.allTimeHigh.price)} $</div>
      </div>
      `;

      cryptocontent.insertAdjacentHTML("beforeend", row);
    });
  };
</script>

{% endblock %}

bank_app/templates/bank_app/employee.html
{% extends "bank_app/base.html" %} {% block content %} {% if costumer.is_employee %}

<h3>Employee Zone ✍️</h3>

<h2>Add user</h2>
<form action="{% url 'bank_app:add_user' %}" method="POST">
  {% csrf_token %}
  <input type="text" name="username" placeholder="username" />
  <input type="text" name="firstname" placeholder="firstname" />
  <input type="text" name="lastname" placeholder="lastname" />
  <input type="text" name="password" placeholder="password" />
  <input type="text" name="email" placeholder="email" />
  {{ costumer_form }}
  <button>Add User</button>
</form>

<h2>All users</h2>

<div class="gridx3" style="display: grid; grid-template-columns: 1fr 1fr 1fr">
  {% for user in users %}

  <div class="user">
    <h4>{{ user.username }}</h4>

    <a href="{{ user.id }}">Account details</a>

    <form action="{% url 'bank_app:change_rank' %}" method="POST">
      {% csrf_token %}
      <div style="display: flex">
        <input type="radio" id="gold" name="rank" value="Gold" />
        <label for="gold">Gold</label>
        <input type="radio" id="silver" name="rank" value="Silver" />
        <label for="silver">Silver</label>
        <input type="radio" id="basic" name="rank" value="Basic" />
        <label for="basic">Basic</label>
        <button>Update</button>
      </div>
      <input type="hidden" name="pk" value="{{ user.pk }}" />
    </form>

    <form action="{% url 'bank_app:add_account' %}" method="POST">
      {% csrf_token %}
      <input type="text" name="account" placeholder="account name" />
      <input type="hidden" name="pk" value="{{ user.pk }}" />
      <button>Add new</button>
    </form>
  </div>

  <div style="margin: 15px 0"></div>

  {% endfor %}
</div>
{% if users.has_previous %}

<a href="{% url 'bank_app:add_user'%}?page={{users.previous_page_number}}">Previous Users</a>
{% endif %} {% if users.has_next %}
<a href="{% url 'bank_app:add_user'%}?page={{users.next_page_number}}">Next Users</a>
{% endif %} {% endif %} {% endblock %}

bank_app/templates/bank_app/index.html
{% extends "bank_app/base.html" %} {% block content %} {% load humanize %}

<h1>Bank of Cold Friday 🤑</h1>
<hr />

<p>Welcome <strong>{{ user }}</strong> 🎉 - <a href="{% url 'bank_app:logout' %}">Log out</a></p>
<a href="{% url 'two_factor:profile' %}">2 factor authentication settings </a>

<p>Your rank: <strong>{{ costumer.rank }} </strong></p>

<hr />

<h3>User Zone 👨</h3>

<a href="{{ user.id }}">My account details</a>

<h2>My Loans</h2>

{% for loan in loans %}

<p>Loan id: {{loan.id}} - {{ loan.name }} // {{ loan.balance|floatformat:2|intcomma }} $</p>

{% endfor %}

<hr />

<h2>My Accounts</h2>

{% for account in accounts %}

<p>Account id: {{account.id}} - {{ account.name }} // {{ account.balance|floatformat:2|intcomma }} $</p>

{% endfor %} {% endblock %}

bank_app/templates/bank_app/loan.html
{% extends "bank_app/base.html" %} {% block content %} {% load humanize %} {% if costumer.can_make_loans %} {{ message }}

<div class="container">
  <div class="loans-overview">
    <h2>My Loans</h2>

    {% for loan in loans %}

    <p>Loan id: {{loan.id}} - {{ loan.name }} // $ {{ loan.balance|floatformat:2|intcomma }}</p>

    {% endfor %}
  </div>

  <div class="accounts-overview">
    <h2>My Accounts</h2>

    {% for account in accounts %}

    <p>Account id: {{account.id}} - {{ account.name }} // $ {{ account.balance|floatformat:2|intcomma }}</p>

    {% endfor %}
  </div>
</div>

<div class="container">
  <div class="create-loan">
    <h2>Create new loan 📝</h2>

    <form action="{% url 'bank_app:make_loan' %}" method="POST">
      {% csrf_token %}
      <input type="text" name="loan_name" placeholder="Loan name" />

      <label>Transfer money to:</label>
      <select name="account_name" placeholder="My accounts">
        {% for account in accounts %}
        <option value="{{ account.id }}">{{ account.name }}</option>
        {% endfor %}
      </select>

      <input type="text" name="text" placeholder="Loan comment" />
      <input type="number" name="amount" placeholder="Amount" />
      <button>Make loan</button>
    </form>
  </div>

  <div class="pay-loan">
    <h2>Pay off loan 💸💰</h2>

    <form action="{% url 'bank_app:pay_loan' %}" method="POST">
      {% csrf_token %}
      <label>My accounts:</label>
      <select name="from_account" placeholder="My accounts">
        {% for account in accounts %}
        <option value="{{ account.id }}">{{ account.name }}</option>
        {% endfor %}
      </select>

      <input type="text" name="regnr" placeholder="Receiver port (port of this running django instance)" />

      <label>My loans:</label>
      <select name="to_account" placeholder="My accounts">
        {% for loan in loans %}
        <option value="{{ loan.id }}">{{ loan.name }}</option>
        {% endfor %}
      </select>

      <input type="text" name="text" placeholder="Transaction comment" />
      <input type="number" name="amount" placeholder="Amount" />
      <button>Send</button>
    </form>
  </div>
</div>

{% else %}

<h2>Sorry, rank too low to make loans</h2>

{% endif %} {% endblock %}

bank_app/templates/bank_app/transfer.html
{% extends "bank_app/base.html" %} {% block content %} {% load humanize %}

<div class="container">
  <div class="accounts-overview">
    <h2>My Accounts</h2>

    {% for account in accounts %}

    <p>Account id: {{account.id}} - {{ account.name }} // $ {{ account.balance|floatformat:2|intcomma }}</p>

    {% endfor %}
  </div>
</div>

<div class="container">
  <div class="transfer">
    <h2>Transfer Money 💸💰</h2>

    <form action="{% url 'bank_app:transfer_money' %}" method="POST">
      {% csrf_token %}
      <label>My accounts:</label>
      <select name="from_account" placeholder="My accounts">
        {% for account in accounts %}
        <option value="{{ account.id }}">{{ account.name }}</option>
        {% endfor %}
      </select>

      <input type="text" name="regnr" placeholder="Receiver port (port of this running django instance)" />
      <input type="text" name="to_account" placeholder="Receiver account id" />
      <input type="text" name="text" placeholder="Transaction comment" />
      <input type="number" name="amount" placeholder="Amount" />
      <button>Send</button>
    </form>
  </div>

  <div class="external">
    <h2>External Money Transfer ❗️💸💰</h2>

    <form action="{% url 'bank_app:external_transfer' %}" method="POST">
      {% csrf_token %}
      <label>My accounts:</label>
      <select name="from_account" placeholder="My accounts">
        {% for account in accounts %}
        <option value="{{ account.id }}">{{ account.name }}</option>
        {% endfor %}
      </select>

      <input type="text" name="to_regnr" placeholder="Receiver port (fx 4000)" maxlength="4" />
      <input type="text" name="to_account" placeholder="Receiver account id" />
      <input type="text" name="text" placeholder="Transaction comment" />
      <input type="number" name="amount" placeholder="Amount" />
      <button>Send</button>
    </form>
  </div>
</div>

{% endblock %}