bank_app/urls.py
from django.urls import path, include
from . import views
from .api import CostumerDetail, CostumerList, LedgerDetail, LedgerList, AccountDetail, AccountList


app_name = 'bank_app'

urlpatterns = [
    path('', views.index, name="index"),
    path('add_user', views.add_user, name="add_user"),
    path('change_rank', views.change_rank, name="change_rank"),
    path('add_account', views.add_account, name="add_account"),
    path('transfer_money', views.transfer_money, name="transfer_money"),
    path('external_transfer', views.external_transfer, name="external_transfer"),
    path('crypto', views.crypto, name="crypto"),
    path('make_loan', views.make_loan, name="make_loan"),
    path('pay_loan', views.pay_loan, name="pay_loan"),
    path('<int:Costumer_id>/', views.account_detail, name="account_detail"),
    path('logout', views.logout, name="logout"),
    path('test_smtp', views.test_smtp, name="test_smtp"),
    path('sendmail/<int:account_id>/', views.sendmail, name="sendmail"),
    # api urls
    path('api/v1/Costumer/<int:pk>/', CostumerDetail.as_view()),
    path('api/v1/Costumer', CostumerList.as_view()),
    path('api/v1/Ledger/<int:pk>/', LedgerDetail.as_view()),
    path('api/v1/Ledger', LedgerList.as_view()),
    path('api/v1/Account/<int:pk>', AccountDetail.as_view()),
    path('api/v1/Account/', AccountList.as_view()),
    path('api/v1/rest-auth/', include('rest_auth.urls')),
    # channel urls
    path('chat/<str:room_name>/', views.room, name='room'),
    path('support_chat', views.support_chat, name="support_chat"),
]

bank_project/urls.py
from django.contrib import admin
from django.urls import path, include
from two_factor.urls import urlpatterns as tf_urls

urlpatterns = [
    path('admin/', admin.site.urls),
    path('bank/', include('bank_app.urls')),
    path('accounts/', include('login_app.urls')),
    path(r'', include(tf_urls)),
    path('api-auth/', include('rest_framework.urls')),



]

login_app/urls.py
from django.urls import path
from . import views


app_name = 'login_app'

urlpatterns = [
    #path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    # path('password_reset/', views.password_reset, name='password_reset'),
    path('sign_up/', views.sign_up, name='sign_up'),
    # path('delete_account/', views.delete_account, name='delete_account'),
]

login_app/models.py
# Create your models here.

login_app/views.py
from django.shortcuts import render, reverse
from django.contrib.auth.models import User
from django.contrib.auth import authenticate, login as dj_login, \
        logout as dj_logout
from django.http import HttpResponseRedirect


# Create your views here.

def login(request):
    context = {}

    if request.method == "POST":
        user = authenticate(
            request,
            username=request.POST['user'],
            password=request.POST['password'])
        if user:
            dj_login(request, user)
            return HttpResponseRedirect(reverse('bank_app:index'))
        else:
            context = {
                'error': 'Bad username or password.'
            }
    return render(request, 'login_app/login.html', context)


def logout(request):
    dj_logout(request)
    return render(request, 'two_factor:login')


def password_reset(request):
    pass


def sign_up(request):
    context = {}
    if request.method == "POST":
        password = request.POST['password']
        confirm_password = request.POST['confirm_password']
        user_name = request.POST['user']
        email = request.POST['email']

        if password == confirm_password:
            if User.objects.create_user(user_name, email, password):

                return HttpResponseRedirect(reverse('login_app:login'))

            else:
                context = {
                    'error': 'Could not create user account \
                            - please try again.'}
        else:
            context = {
                'error': 'Passwords did not match. Please try again.'
            }

    return render(request, 'login_app/sign_up.html', context)


def delete_account(request):
    pass

login_app/templates/login_app/login.html
<!DOCTYPE html>
<html lang="en">
<head>
   <meta charset="UTF-8">
   <meta name="viewport" content="width=device-width, initial-scale=1.0">
   <title>Login</title>
</head>
<body>
   <h1>Login</h1>
   <a href="{% url 'login_app:sign_up' %}">Sign Up</a>
   <hr />
      <form action="{% url 'login_app:login' %}" method="POST">
            {% csrf_token %}
            <input type="text" name="user" placeholder="User Name">
            <input type="password" name="password" placeholder="Password">
            <button>Login</button>
      </form>
   <hr />
   {% if error %}
      {{ error }}
   {% endif %}
</body>
</html>

login_app/templates/login_app/sign_up.html
<!DOCTYPE html>
<html lang="en">
<head>
   <meta charset="UTF-8">
   <meta name="viewport" content="width=device-width, initial-scale=1.0">
   <title>Sign Up</title>
</head>
<body>
   <h1>Sign Up</h1>
   <a href="{% url 'login_app:login' %}">Login</a>
   <hr />
   <form action="{% url 'login_app:sign_up' %}" method="POST">
      {% csrf_token %}
      <input type="text" name="user" placeholder="User Name">
      <input type="email" name="email" placeholder="Email Address">
      <input type="password" name="password" placeholder="Password">
      <input type="password" name="confirm_password" placeholder="Confirm Password">
      <input type="text" name="phone" placeholder="phone">
      <input type="text" name="rank" placeholder="rank">
      <button>Sign Up</button>
   </form>
   <hr />
   {% if error %}
      {{ error }}
   {% endif %}
</body>
</html>